server:
  port: 8080
  servlet:
    context-path: /api
    # cookie过期时间30天
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: shea-picture
  datasource:
    url: jdbc:mysql://192.168.100.104:3306/shea_picture?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    database: 0
    host: 192.168.100.104
    port: 6379
    password: xgw18720322169.
    timeout: 5000
  session:
    store-type: redis
    # session过期时间 30天
    timeout: 2592000
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false  # 显式关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 云图库接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.shea.picture.sheapicture.controller
